import { 
  Activity, 
  Bird,
  GraduationCap,
  Building,
  Phone,
  Folder,
  Church,
  Volume2,
  Laptop,
  Monitor,
  Wifi,
  Smartphone,
  Power,
  DollarSign,
  MousePointer,
  Layers3,
  AppWindow,
  Book,
  Gem,
  Calculator,
  Camera,
  Smile,
  Frown,
  Heart,
  Leaf,
  PartyPopper,
  Rocket,
  Apple,
  Coffee,
  Bed,
  Trophy,
  Dice5,
  Waves,
  Globe,
  Palette,
  Pencil,
} from "lucide-react";

export const icons: Record<string, React.ReactNode> = {
  activity: <Activity />,
  bird: <Bird />,
  graduationCap: <GraduationCap />,
  building: <Building />,
  phone: <Phone />,
  folder: <Folder />,
  church: <Church />,
  volume2: <Volume2 />,
  laptop: <Laptop />,
  monitor: <Monitor />,
  wifi: <Wifi />,
  smartphone: <Smartphone />,
  power: <Power />,
  dollarSign: <DollarSign />,
  mousePointer: <MousePointer />,
  layers3: <Layers3 />,
  appWindow: <AppWindow />,
  book: <Book />,
  gem: <Gem />,
  calculator: <Calculator />,
  camera: <Camera />,
  smile: <Smile />,
  frown: <Frown />,
  heart: <Heart />,
  leaf: <Leaf />,
  partyPopper: <PartyPopper />,
  rocket: <Rocket />,
  apple: <Apple />,
  coffee: <Coffee />,
  bed: <Bed />,
  trophy: <Trophy />,
  dice5: <Dice5 />,
  waves: <Waves />,
  globe: <Globe />,
  palette: <Palette />,
  pencil: <Pencil />,
}